#!/bin/sh -e
### BEGIN INIT INFO
# Provides: host_file_update
# Required-Start: $network
# Required-Stop: $network
# Required-Reload: $network
# Default-Start: 2 3 4 5
# Default-Stop:	0 1 6
# Description: Changes the hosts file to match DHCP Ip number
#
### END INIT INFO
#
set -e

case "$1" in
  start)
# Set the Client's hostname
myHostName=$(cat /etc/hostname)
myDomainName=$(domainname)
echo "$myDomainName is being used as domain name"
myFQDN=$myHostName.$myDomainName
domainname $myDomainName
# Lookup the current loopback IP Address and strip it out of the result
loaddr4=$(/sbin/ifconfig lo | grep 'inet '| cut -d: -f2 | awk '{ print $2}')
loaddr6=$(/sbin/ifconfig lo | grep 'inet6 ' | awk '{ print $2}')
# Lookup the current IP Address and strip it out of the result
ipaddr4=$(/sbin/ifconfig | grep 'inet '| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $2}')
ipaddr6=$(/sbin/ifconfig | grep 'inet6 '| grep -v '::1' | awk '{ print $2}') 
# erase /etc/hosts and create a new one
rm -rf /etc/hosts
touch /etc/hosts
#  Add the loopback IP Address back to /etc/hosts
echo "$loaddr4 localhost localhost.localdomain" >> /etc/hosts
echo "$loaddr6 localhost localhost.localdomain ip6-localhost ip6-loopback" >> /etc/hosts
echo " " >> /etc/hosts
#  Add the Client's current IP Address and HostName to /etc/hosts
echo "$ipaddr4 $myFQDN $myHostName ${myFQDN^^} ${myHostName^^}" >> /etc/hosts
echo "$ipaddr6 $myFQDN $myHostName ${myFQDN^^} ${myHostName^^}" >> /etc/hosts
exit 0
;;
    stop)
# Set the Client's hostname
myHostName=$(cat /etc/hostname)
myDomainName=$(domainname)
echo "$myDomainName is being used as domain name"
myFQDN=$myHostName.$myDomainName
domainname $myDomainName
# Lookup the current IP Address and strip it out of the result
loaddr4=$(/sbin/ifconfig lo | grep 'inet '| cut -d: -f2 | awk '{ print $2}')
loaddr6=$(/sbin/ifconfig lo | grep 'inet6 ' | awk '{ print $2}')
rm -rf /etc/hosts
touch /etc/hosts
#  Add the Client's loopback IP Address to HostName at /etc/hosts
echo "$loaddr4 localhost localhost.localdomain" >> /etc/hosts
echo "$loaddr6 localhost localhost.localdomain ip6-localhost ip6-loopback" >> /etc/hosts
echo " " >> /etc/hosts
echo "$loaddr4 $myFQDN $myHostName ${myFQDN^^} ${myHostName^^}" >> /etc/hosts
echo "$loaddr6 $myFQDN $myHostName ${myFQDN^^} ${myHostName^^}" >> /etc/hosts
exit 0
;;
  restart)
# Set the Client's hostname
myHostName=$(cat /etc/hostname)
myDomainName=$(domainname)
echo "$myDomainName is being used as domain name"
myFQDN=$myHostName.$myDomainName
domainname $myDomainName
# Lookup the current loopback IP Address and strip it out of the result
loaddr4=$(/sbin/ifconfig lo | grep 'inet '| cut -d: -f2 | awk '{ print $2}')
loaddr6=$(/sbin/ifconfig lo | grep 'inet6 ' | awk '{ print $2}')
# Lookup the current IP Address and strip it out of the result
ipaddr4=$(/sbin/ifconfig | grep 'inet '| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $2}')
ipaddr6=$(/sbin/ifconfig | grep 'inet6 '| grep -v '::1' | awk '{ print $2}') 
# erase /etc/hosts and create a new one
rm -rf /etc/hosts
touch /etc/hosts
#  Add the loopback IP Address back to /etc/hosts
echo "$loaddr4 localhost localhost.localdomain" >> /etc/hosts
echo "$loaddr6 localhost localhost.localdomain ip6-localhost ip6-loopback" >> /etc/hosts
echo " " >> /etc/hosts
#  Add the server's current IP Address and HostName to /etc/hosts
echo "$ipaddr4 $myFQDN $myHostName ${myFQDN^^} ${myHostName^^}" >> /etc/hosts
echo "$ipaddr6 $myFQDN $myHostName ${myFQDN^^} ${myHostName^^}" >> /etc/hosts
exit 0
;;
    *)
  echo "Use: /etc/init.d/host_file_update {start|stop|restart}"
;;
esac
exit 0

# /etc/init.d/host_file_update
# needs
# /lib/systemd/system/host_file_update.service
#